version: '3.8'

services:
  backend:
    build:
      context: ./backend_laravel
    ports:
      - "8081:80"
    depends_on:
      - database
    command: php artisan serve --host=0.0.0.0 --port=80
    volumes:
      - ./backend_laravel:/var/www/html

  frontend:
    build:
      context: ./frontend_react
    ports:
      - "8080:5173"

  database:
    image: mysql:latest
    ports:
      - "3307:3306" # Changed port mapping
    environment:
      MYSQL_DATABASE: cfp_test
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
