version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST: db
      - DB_PORT: 3306
      - DB_DATABASE: ${DB_DATABASE}
      - DB_USERNAME: ${DB_USERNAME}
      - DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
